----- CALCULAR IMPUESTOS
CREATE OR REPLACE TRIGGER TRIG_IMPUESTO_COMPRA
    BEFORE INSERT ON DETALLE_COMPRA FOR EACH ROW
BEGIN
    IF :NEW.TOTAL IS NULL THEN
        :NEW.TOTAL := :NEW.CANTIDAD*:NEW.PRECIO_PRODUCTO;
        
        BEGIN
            UPDATE_PRECIO_COMPRA(:NEW.PRODUCTO_ID_PRODUCTO,:NEW.PRECIO_PRODUCTO);
            UPDATE_PRECIO_VENTA(:NEW.PRODUCTO_ID_PRODUCTO);
        END; 
        
    ELSE
        RAISE_APPLICATION_ERROR(-20000,'LA CANTIDAD ES DISTINTA DE NULL');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIG_IMPUESTO_VENTA
    BEFORE INSERT ON DETALLE_VENTA FOR EACH ROW
BEGIN

    IF :NEW.TOTAL IS NULL THEN
        :NEW.TOTAL := :NEW.CANTIDAD*:NEW.PRECIO_VENTA;
    ELSE
        RAISE_APPLICATION_ERROR(-20000,'LA CANTIDAD ES DISTINTA DE NULL');
    END IF;

END;
/

----- ACTUALIZAR STOCK
CREATE OR REPLACE TRIGGER TRIG_STOCK_VENTA
    BEFORE INSERT ON DETALLE_VENTA FOR EACH ROW
DECLARE V_CANTIDAD NUMBER(12);
BEGIN

SELECT EXISTENCIA INTO V_CANTIDAD FROM PRODUCTO 
WHERE PRODUCTO.ID_PRODUCTO LIKE :NEW.PRODUCTO_ID_PRODUCTO;

IF :NEW.CANTIDAD <= 0 THEN
    RAISE_APPLICATION_ERROR(-20000,'La cantidad debe ser mayor que 0');
    ELSE IF :NEW.CANTIDAD <= V_CANTIDAD THEN
            UPDATE PRODUCTO
            SET EXISTENCIA= EXISTENCIA - :NEW.CANTIDAD
            WHERE ID_PRODUCTO = :NEW.PRODUCTO_ID_PRODUCTO;
        ELSE IF :NEW.CANTIDAD >= V_CANTIDAD THEN
            RAISE_APPLICATION_ERROR(-20000,'La cantidad excede el stock disponible');
         END IF;
    END IF;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIG_STOCK_COMPRA
    BEFORE INSERT ON DETALLE_COMPRA FOR EACH ROW
BEGIN

IF :NEW.CANTIDAD <= 0 THEN
    RAISE_APPLICATION_ERROR(-20000,'La cantidad debe ser mayor que 0');
    ELSE
            UPDATE PRODUCTO
            SET EXISTENCIA= EXISTENCIA + :NEW.CANTIDAD
            WHERE ID_PRODUCTO = :NEW.PRODUCTO_ID_PRODUCTO;
    END IF;
END;
/

------AGREGAR PRECIO DE VENTA
CREATE OR REPLACE TRIGGER TRIG_AGREGAR_PRECIO_VENTA
     BEFORE INSERT ON PRODUCTO FOR EACH ROW
BEGIN

    IF :NEW.PRECIO_VENTA IS NULL  THEN
        :NEW.PRECIO_VENTA := :NEW.PRECIO_COMPRA+(:NEW.PRECIO_COMPRA*0.37); 
    ELSE 
        RAISE_APPLICATION_ERROR(-20000,'LA CANTIDAD ES DISTINTA DE NULL');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIG_VENTA_ANULADO
     BEFORE DELETE ON FACTURA_VENTA FOR EACH ROW
BEGIN
    INSERT INTO VENTA_ANULADA VALUES(NULL, :OLD.FECHA_VENTA, :OLD.NO_FACTURA);
    DELETE FROM DETALLE_VENTA WHERE DETALLE_VENTA.FACTURA_VENTA_ID_VENTA = :OLD.ID_VENTA;
    DELETE FROM IMPUESTO_VENTA WHERE IMPUESTO_VENTA.FACTURA_ID_VENTA = :OLD.ID_VENTA;
END;
/

CREATE OR REPLACE TRIGGER TRIG_COMPRA_ANULADO
     BEFORE DELETE ON FACTURA_COMPRA FOR EACH ROW
BEGIN
    INSERT INTO COMPRA_ANULADA VALUES(NULL, :OLD.FECHA_COMPRA, :OLD.NO_COMPRA);
    DELETE FROM DETALLE_COMPRA WHERE DETALLE_COMPRA.FACTURA_COMPRAS_ID_COMPRA = :OLD.ID_COMPRA;
    DELETE FROM IMPUESTO_COMPRA WHERE IMPUESTO_COMPRA.FACTURA_ID_COMPRA = :OLD.ID_COMPRA;
END;
/