CREATE TABLE VENTA_ANULADA (
ID_VENTA_ANULADA      NUMBER(*,0) NOT NULL,
FECHA_VENTA     DATE DEFAULT SYSDATE,
FACTURA_VENTA   VARCHAR(25) NOT NULL
);
ALTER TABLE VENTA_ANULADA ADD CONSTRAINT VENTA_ANULADA_PK PRIMARY KEY ( ID_VENTA_ANULADA );

CREATE TABLE COMPRA_ANULADA (
ID_COMPRA_ANULADA      NUMBER(*,0) NOT NULL,
FECHA_COMPRA     DATE DEFAULT SYSDATE,
FACTURA_COMPRA   VARCHAR(25) NOT NULL
);
ALTER TABLE COMPRA_ANULADA ADD CONSTRAINT COMPRA_ANULADA_PK PRIMARY KEY ( ID_COMPRA_ANULADA );

CREATE TABLE CATEGORIA (
    ID_CATEGORIA           NUMBER(*, 0) NOT NULL,
    NOMBRE_CATEGORIA       NVARCHAR2(50) NOT NULL,
    DESCRIPCION_CATEGORIA  NVARCHAR2(150) NOT NULL
);
ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( ID_CATEGORIA );

CREATE TABLE CLIENTE (
    ID_CLIENTE         NUMBER(*, 0) NOT NULL,
    NIT_CLIENTE        NVARCHAR2(50) CONSTRAINT CLIENTE_UK UNIQUE,
    NOMBRE_CLIENTE     NVARCHAR2(50) NOT NULL,
    DIRECCION_CLIENTE  NVARCHAR2(150) NOT NULL,
    TELEFONO           NUMBER(*, 0) NOT NULL
);
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( ID_CLIENTE );

CREATE TABLE DETALLE_COMPRA (
    ID_DET_COMPRA              NUMBER(*, 0)  NOT NULL,
    CANTIDAD                   NUMBER(*, 0)  NOT NULL,
    PRECIO_PRODUCTO            NUMBER(12, 2) NOT NULL,
    TOTAL                      NUMBER(12, 2) NOT NULL,
    PRODUCTO_ID_PRODUCTO       NUMBER(*, 0)  NOT NULL,
    FACTURA_COMPRAS_ID_COMPRA  NUMBER(*, 0)  NOT NULL
);
ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT DETALLE_COMPRA_PK PRIMARY KEY ( ID_DET_COMPRA,
                                                                          FACTURA_COMPRAS_ID_COMPRA );

CREATE TABLE IMPUESTO_COMPRA (
    ID_IMPUESTO_COMPRA          NUMBER(*, 0)  NOT NULL,
    FACTURA_ID_COMPRA           NUMBER(*, 0)  NOT NULL,
    IVA_COMPRA                  NUMBER(12, 2) NOT NULL,
    ISR_COMPRA                  NUMBER(12, 2) NOT NULL
);
ALTER TABLE IMPUESTO_COMPRA ADD CONSTRAINT IMPUESTO_COMPRA_PK PRIMARY KEY ( ID_IMPUESTO_COMPRA,
                                                                        FACTURA_ID_COMPRA);
CREATE TABLE IMPUESTO_VENTA (
    ID_IMPUESTO_VENTA          NUMBER(*, 0)  NOT NULL,
    FACTURA_ID_VENTA           NUMBER(*, 0)  NOT NULL,
    ISR_VENTA                  NUMBER(12, 2) NOT NULL,
    IVA_VENTA                  NUMBER(12, 2) NOT NULL
    
);
ALTER TABLE IMPUESTO_VENTA ADD CONSTRAINT IMPUESTO_VENTA_PK PRIMARY KEY ( ID_IMPUESTO_VENTA,
                                                                        FACTURA_ID_VENTA);
CREATE TABLE DETALLE_VENTA (
    ID_DET_VENTA            NUMBER(*, 0)  NOT NULL,
    PRODUCTO_ID_PRODUCTO    NUMBER(*, 0)  NOT NULL,
    PRECIO_VENTA            NUMBER(12, 2) NOT NULL,
    CANTIDAD                NUMBER(*, 0)  NOT NULL,
    TOTAL                   NUMBER(12, 2) NOT NULL,
    FACTURA_VENTA_ID_VENTA  NUMBER(*, 0)  NOT NULL
);
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY ( ID_DET_VENTA,
                                                                        FACTURA_VENTA_ID_VENTA );

CREATE TABLE FACTURA_COMPRA (
    ID_COMPRA               NUMBER(*, 0) NOT NULL,
    NO_COMPRA               NUMBER(*, 0) NOT NULL,
    FECHA_COMPRA            DATE DEFAULT SYSDATE,
    PROVEEDOR_ID_PROVEEDOR  NUMBER(*, 0) NOT NULL,
    USERS_ID                NUMBER(19) NOT NULL
);
ALTER TABLE FACTURA_COMPRA ADD CONSTRAINT FACTURA_COMPRAS_PK PRIMARY KEY ( ID_COMPRA );

CREATE TABLE FACTURA_VENTA (
    ID_VENTA            NUMBER(*, 0) NOT NULL,
    NO_FACTURA           NUMBER(*, 0) CONSTRAINT FACTURA_UK UNIQUE,
    FECHA_VENTA         DATE DEFAULT SYSDATE,
    CLIENTE_ID_CLIENTE  NUMBER(*, 0) NOT NULL,
    USERS_ID            NUMBER(19) NOT NULL
);
ALTER TABLE FACTURA_VENTA ADD CONSTRAINT FACTURA_VENTA_PK PRIMARY KEY ( ID_VENTA );

CREATE TABLE FAILED_JOBS (
    ID          NUMBER(19) NOT NULL,
    UUID        VARCHAR2(255 BYTE) NOT NULL,
    CONNECTION  CLOB NOT NULL,
    QUEUE       CLOB NOT NULL,
    PAYLOAD     CLOB NOT NULL,
    EXCEPTION   CLOB NOT NULL,
    FAILED_AT   TIMESTAMP NOT NULL
);
ALTER TABLE FAILED_JOBS ADD CONSTRAINT FAILED_JOBS_PK PRIMARY KEY ( ID );
ALTER TABLE FAILED_JOBS ADD CONSTRAINT FAILED_JOBS_UUID_UN UNIQUE ( UUID );

CREATE TABLE MIGRATIONS (
    ID         NUMBER(10) NOT NULL,
    MIGRATION  VARCHAR2(255 BYTE) NOT NULL,
    BATCH      NUMBER(10) NOT NULL
);
ALTER TABLE MIGRATIONS ADD CONSTRAINT MIGRATIONS_PK PRIMARY KEY ( ID );

CREATE TABLE PASSWORD_RESETS (
    EMAIL       VARCHAR2(255 BYTE) NOT NULL,
    TOKEN       VARCHAR2(255 BYTE) NOT NULL,
    CREATED_AT  TIMESTAMP
);

CREATE TABLE PERSONAL_ACCESS_TOKENS (
    ID              NUMBER(19) NOT NULL,
    TOKENABLE_TYPE  VARCHAR2(255 BYTE) NOT NULL,
    TOKENABLE_ID    NUMBER(19) NOT NULL,
    NAME            VARCHAR2(255 BYTE) NOT NULL,
    TOKEN           VARCHAR2(64 BYTE) NOT NULL,
    ABILITIES       CLOB,
    LAST_USED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP
);
ALTER TABLE PERSONAL_ACCESS_TOKENS ADD CONSTRAINT PERSONAL_ACCESS_TOKENS_PK PRIMARY KEY ( ID );
ALTER TABLE PERSONAL_ACCESS_TOKENS ADD CONSTRAINT PERSONAL_ACCESS_TOKEN_UN UNIQUE ( TOKEN );

CREATE TABLE PRODUCTO (
    ID_PRODUCTO             NUMBER(*, 0) NOT NULL,
    NOMBRE_PRODUCTO         NVARCHAR2(50) NOT NULL,
    DESCRIPCION_PRODUCTO    NVARCHAR2(150) NOT NULL,
    EXISTENCIA              NUMBER(*, 0) NOT NULL,
    PRECIO_COMPRA           NUMBER(12, 2) NOT NULL,
    PRECIO_VENTA            NUMBER(12, 2) NOT NULL,
    CATEGORIA_ID_CATEGORIA  NUMBER(*, 0) NOT NULL
);
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( ID_PRODUCTO );

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR         NUMBER(*, 0) NOT NULL,
    NIT_PROVEEDOR        NVARCHAR2(50) CONSTRAINT PROVEEDOR_UK UNIQUE,
    NOMBRE_PROVEEDOR     NVARCHAR2(50) NOT NULL,
    DIRECCION_PROVEEDOR  NVARCHAR2(150) NOT NULL,
    TELEFONO             NUMBER(*, 0) NOT NULL
);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( ID_PROVEEDOR );

CREATE TABLE SESSIONS (
    ID             VARCHAR2(255 BYTE) NOT NULL,
    USER_ID        NUMBER(19),
    IP_ADDRESS     VARCHAR2(45 BYTE),
    USER_AGENT     CLOB,
    PAYLOAD        CLOB NOT NULL,
    LAST_ACTIVITY  NUMBER(10) NOT NULL
);
ALTER TABLE SESSIONS ADD CONSTRAINT SESSIONS_PK PRIMARY KEY ( ID );

CREATE TABLE USERS (
    ID                         NUMBER(19) NOT NULL,
    NAME                       VARCHAR2(255 BYTE) NOT NULL,
    EMAIL                      VARCHAR2(255 BYTE) NOT NULL,
    EMAIL_VERIFIED_AT          TIMESTAMP,
    PASSWORD                   VARCHAR2(255 BYTE) NOT NULL,
    REMEMBER_TOKEN             VARCHAR2(100 BYTE),
    CURRENT_TEAM_ID            NUMBER(19),
    PROFILE_PHOTO_PATH         CLOB,
    CREATED_AT                 TIMESTAMP,
    UPDATED_AT                 TIMESTAMP,
    TWO_FACTOR_SECRET          CLOB,
    TWO_FACTOR_RECOVERY_CODES  CLOB
);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY ( ID );
ALTER TABLE USERS ADD CONSTRAINT USERS_EMAIL_UN UNIQUE ( EMAIL );

------- FOREIGN KEYS
ALTER TABLE DETALLE_COMPRA
    ADD CONSTRAINT DETALLE_COMPRA_FACTURA_FK FOREIGN KEY ( FACTURA_COMPRAS_ID_COMPRA )
        REFERENCES FACTURA_COMPRA ( ID_COMPRA );

ALTER TABLE DETALLE_COMPRA
    ADD CONSTRAINT DETALLE_COMPRA_PRODUCTO_FK FOREIGN KEY ( PRODUCTO_ID_PRODUCTO )
        REFERENCES PRODUCTO ( ID_PRODUCTO );

ALTER TABLE DETALLE_VENTA
    ADD CONSTRAINT DETALLE_VENTA_FACTURA_VENTA_FK FOREIGN KEY ( FACTURA_VENTA_ID_VENTA )
        REFERENCES FACTURA_VENTA ( ID_VENTA );

ALTER TABLE DETALLE_VENTA
    ADD CONSTRAINT DETALLE_VENTA_PRODUCTO_FK FOREIGN KEY ( PRODUCTO_ID_PRODUCTO )
        REFERENCES PRODUCTO ( ID_PRODUCTO );

ALTER TABLE FACTURA_COMPRA
    ADD CONSTRAINT FACTURA_COMPRAS_PROVEEDOR_FK FOREIGN KEY ( PROVEEDOR_ID_PROVEEDOR )
        REFERENCES PROVEEDOR ( ID_PROVEEDOR );

ALTER TABLE FACTURA_COMPRA
    ADD CONSTRAINT FACTURA_COMPRAS_USERS_FK FOREIGN KEY ( USERS_ID )
        REFERENCES USERS ( ID );

ALTER TABLE FACTURA_VENTA
    ADD CONSTRAINT FACTURA_VENTA_CLIENTE_FK FOREIGN KEY ( CLIENTE_ID_CLIENTE )
        REFERENCES CLIENTE ( ID_CLIENTE );

ALTER TABLE FACTURA_VENTA
    ADD CONSTRAINT FACTURA_VENTA_USERS_FK FOREIGN KEY ( USERS_ID )
        REFERENCES USERS ( ID );

ALTER TABLE PRODUCTO
    ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY ( CATEGORIA_ID_CATEGORIA )
        REFERENCES CATEGORIA ( ID_CATEGORIA );

ALTER TABLE IMPUESTO_COMPRA
    ADD CONSTRAINT DETALLE_COMPRA_FK FOREIGN KEY (FACTURA_ID_COMPRA)
        REFERENCES FACTURA_COMPRA (ID_COMPRA);
        
ALTER TABLE IMPUESTO_VENTA
    ADD CONSTRAINT DETALLE_VENTA_FK FOREIGN KEY (FACTURA_ID_VENTA)
        REFERENCES FACTURA_VENTA (ID_VENTA);